export const geCategories: Record<string, string> = {
  "GE-1A": "Ia. Writing 1A",
  "GE-1B": "Ib. Writing 1B",
  "GE-2": "II. Science and Technology",
  "GE-3": "III. Social and Behavioral Sciences",
  "GE-4": "IV. Arts and Humanities",
  "GE-5A": "Va. Quantitative, Symbolic, and Computational Reasoning",
  "GE-5B": "Vb. Quantitative, Symbolic, and Computational Reasoning",
  "GE-6": "VI. Language Other Than English",
  "GE-7": "VII. Multicultural Studies",
  "GE-8": "VIII. International/Global Issues",
};

export const departments: Record<string, string> = {
  "AC ENG": "Academic English & ESL",
  AFAM: "African American Studies",
  ANATOMY: "Anatomy & Neurobiology",
  ANTHRO: "Anthropology",
  ARABIC: "Arabic",
  ARMN: "Armenian",
  ART: "Art",
  "ART HIS": "Art History",
  ASIANAM: "Asian American Studies",
  BANA: "Business Analytics",
  "BIO SCI": "Biological Sciences",
  BIOCHEM: "Biochemistry",
  BME: "Biomedical Engineering",
  CBE: "Chemical & Biomolecular Engineering",
  CBEMS: "Chemical Engineering & Materials Science",
  "CHC/LAT": "Chicano/Latino Studies",
  CHEM: "Chemistry",
  CHINESE: "Chinese",
  CLASSIC: "Classical Studies",
  "CLT&THY": "Culture & Theory",
  COGS: "Cognitive Sciences",
  "COM LIT": "Comparative Literature",
  COMPSCI: "Computer Science",
  "CRM/LAW": "Criminology, Law & Society",
  CSE: "Computer Science & Engineering",
  DANCE: "Dance",
  DATA: "Data Science",
  "DEV BIO": "Developmental & Cell Biology",
  DRAMA: "Drama",
  "E ASIAN": "East Asian Studies",
  EARTHSS: "Earth System Science",
  EAS: "East Asian Studies",
  "ECO EVO": "Ecology & Evolutionary Biology",
  ECON: "Economics",
  ECPS: "Embedded & Cyber-Physical Systems",
  EDUC: "Education",
  EECS: "Electrical Engineering & Computer Science",
  EHS: "Environmental Health Sciences",
  ENGLISH: "English",
  ENGR: "Engineering",
  ENGRCEE: "Civil & Environmental Engineering",
  ENGRMAE: "Mechanical & Aerospace Engineering",
  ENGRMSE: "Materials Science & Engineering",
  EPIDEM: "Epidemiology",
  "EURO ST": "European Studies",
  FIN: "Finance",
  "FLM&MDA": "Film & Media Studies",
  FRENCH: "French",
  GDIM: "Game Design & Interactive Media",
  "GEN&SEX": "Gender & Sexuality Studies",
  GERMAN: "German",
  "GLBL ME": "Global Middle East Studies",
  GLBLCLT: "Global Cultures",
  GREEK: "Greek",
  HEBREW: "Hebrew",
  HISTORY: "History",
  HUMAN: "Humanities",
  "I&C SCI": "Information & Computer Science",
  IN4MATX: "Informatics",
  INNO: "Innovation",
  "INTL ST": "International Studies",
  ITALIAN: "Italian",
  JAPANSE: "Japanese",
  KOREAN: "Korean",
  LATIN: "Latin",
  LINGUIS: "Linguistics",
  "LIT JRN": "Literary Journalism",
  LPS: "Logic & Philosophy of Science",
  LSCI: "Language Science",
  "M&MG": "Microbiology & Molecular Genetics",
  MATH: "Mathematics",
  "MED HUM": "Medical Humanities",
  MGMT: "Management",
  "MGMT EP": "Executive MBA",
  "MGMT FE": "Fully Employed MBA",
  "MGMT HC": "Health Care MBA",
  MGMTMBA: "Master of Business Administration",
  MGMTPHD: "Management PhD",
  "MOL BIO": "Molecular Biology",
  MPAC: "Master of Professional Accountancy",
  MSE: "Materials Science & Engineering",
  MUSIC: "Music",
  "NET SYS": "Networked Systems",
  NEURBIO: "Neurobiology & Behavior",
  "NUR SCI": "Nursing Science",
  PATH: "Pathology",
  "PED GEN": "Pediatric Genetics",
  PERSIAN: "Persian",
  PHARM: "Pharmacology",
  PHILOS: "Philosophy",
  PHMD: "Pharmaceutical Management",
  PHRMSCI: "Pharmaceutical Sciences",
  "PHY SCI": "Physical Science",
  PHYSICS: "Physics",
  PHYSIO: "Physiology & Biophysics",
  "POL SCI": "Political Science",
  PSCI: "Psychological Science",
  "PSY BEH": "Psychology & Social Behavior",
  PSYCH: "Psychology",
  "PUB POL": "Public Policy",
  PUBHLTH: "Public Health",
  "REL STD": "Religious Studies",
  RUSSIAN: "Russian",
  "SOC SCI": "Social Science",
  SOCECOL: "Social Ecology",
  SOCIOL: "Sociology",
  SPANISH: "Spanish",
  SPPS: "Social Policy & Public Service",
  STATS: "Statistics",
  SWE: "Software Engineering",
  TOX: "Toxicology",
  "UNI AFF": "University Affairs",
  "UNI STU": "University Studies",
  UPPP: "Urban Planning & Public Policy",
  VIETMSE: "Vietnamese",
  "VIS STD": "Visual Studies",
  "WOMN ST": "Women's Studies",
  WRITING: "Writing",
};
