export const initialFilter = {
  geCategory: "",
  ABRatio: 0,
  timeFrame: "",
  department: "",
  multipleGE: false,
};

export const geCategories: Record<string, string> = {
  "GE-1A": "Ia. Writing 1A",
  "GE-1B": "Ib. Writing 1B",
  "GE-2": "II. Science and Technology",
  "GE-3": "III. Social and Behavioral Sciences",
  "GE-4": "IV. Arts and Humanities",
  "GE-5A": "Va. Quantitative, Symbolic, and Computational Reasoning",
  "GE-5B": "Vb. Quantitative, Symbolic, and Computational Reasoning",
  "GE-6": "VI. Language Other Than English",
  "GE-7": "VII. Multicultural Studies",
  "GE-8": "VIII. International/Global Issues",
};

export const departments: Record<string, string> = {
  "AC ENG": "Academic English & ESL",
  AFAM: "African American Studies",
  ANTHRO: "Anthropology",
  ARABIC: "Arabic",
  ARMN: "Armenian",
  ART: "Art",
  "ART HIS": "Art History",
  ASIANAM: "Asian American Studies",
  "BIO SCI": "Biological Sciences",
  BIOCHEM: "Biochemistry",
  BME: "Biomedical Engineering",
  "CHC/LAT": "Chicano/Latino Studies",
  CHEM: "Chemistry",
  CHINESE: "Chinese",
  CLASSIC: "Classical Studies",
  "CLT&THY": "Culture & Theory",
  COGS: "Cognitive Sciences",
  "COM LIT": "Comparative Literature",
  COMPSCI: "Computer Science",
  "CRM/LAW": "Criminology, Law & Society",
  DANCE: "Dance",
  DATA: "Data Science",
  DRAMA: "Drama",
  EARTHSS: "Earth System Science",
  EAS: "East Asian Studies",
  ECON: "Economics",
  EDUC: "Education",
  ENGLISH: "English",
  ENGR: "Engineering",
  ENGRCEE: "Civil & Environmental Engineering",
  "EURO ST": "European Studies",
  "FLM&MDA": "Film & Media Studies",
  FRENCH: "French",
  GDIM: "Game Design & Interactive Media",
  "GEN&SEX": "Gender & Sexuality Studies",
  GERMAN: "German",
  "GLBL ME": "Global Middle East Studies",
  GLBLCLT: "Global Cultures",
  GREEK: "Greek",
  HISTORY: "History",
  HUMAN: "Humanities",
  "I&C SCI": "Information & Computer Science",
  IN4MATX: "Informatics",
  "INTL ST": "International Studies",
  ITALIAN: "Italian",
  JAPANSE: "Japanese",
  KOREAN: "Korean",
  LATIN: "Latin",
  "LIT JRN": "Literary Journalism",
  LPS: "Logic & Philosophy of Science",
  LSCI: "Language Science",
  "M&MG": "Microbiology & Molecular Genetics",
  MATH: "Mathematics",
  "MED HUM": "Medical Humanities",
  MGMT: "Management",
  "MOL BIO": "Molecular Biology",
  MSE: "Materials Science & Engineering",
  MUSIC: "Music",
  "NET SYS": "Networked Systems",
  NEURBIO: "Neurobiology & Behavior",
  "NUR SCI": "Nursing Science",
  PATH: "Pathology",
  "PED GEN": "Pediatric Genetics",
  PERSIAN: "Persian",
  PHARM: "Pharmacology",
  PHILOS: "Philosophy",
  PHMD: "Pharmaceutical Management",
  PHRMSCI: "Pharmaceutical Sciences",
  "PHY SCI": "Physical Science",
  PHYSICS: "Physics",
  "POL SCI": "Political Science",
  PSCI: "Psychological Science",
  PSYCH: "Psychology",
  "PUB POL": "Public Policy",
  PUBHLTH: "Public Health",
  "REL STD": "Religious Studies",
  RUSSIAN: "Russian",
  "SOC SCI": "Social Science",
  SOCECOL: "Social Ecology",
  SOCIOL: "Sociology",
  SPANISH: "Spanish",
  SPPS: "Social Policy & Public Service",
  STATS: "Statistics",
  "UNI AFF": "University Affairs",
  "UNI STU": "University Studies",
  UPPP: "Urban Planning & Public Policy",
  VIETMSE: "Vietnamese",
  WRITING: "Writing",
};
